version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8.2-alpine3.17
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            OPENAI_API_KEY: ""
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
